// src/components/home/NavBarHome.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-nav">
        <div class="container">
            <a class="navbar-brand d-flex gap-1" href="/">
                <img :src="logoSrc" width="50" height="50" class="d-inline-block align-top" alt="Logo" />
                <h3 class="m-auto">Divine Desk</h3>
            </a>
            <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#basic-navbar-nav" aria-controls="basic-navbar-nav" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="basic-navbar-nav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="/contact-interest">Contato</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>

<script setup lang="js">
import { computed } from 'vue';

const logoSrc = computed(() => import.meta.env.BASE_URL + 'src/assets/img/logo.png');
</script>

<style scoped>
</style>

// src/Components/Home/NavBarHome.tsx
import { Container, Nav, Navbar } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';

function NavbarHome() {
  return (
    <Navbar className="bg-nav" variant="dark" expand="lg">
      <Container>
        <Navbar.Brand href="/" className='d-flex gap-1'>
          <img
            src={`${process.env.PUBLIC_URL}/img/logo.png`}
            width="50"
            height="50"
            className="d-inline-block align-top"
            alt="Logo"
          />
          <h3 className='m-auto'>Divine Desk</h3>
        </Navbar.Brand>
        <Navbar.Toggle aria-controls="basic-navbar-nav" className="custom-toggler" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="ms-auto">
            <Nav.Link href="/" className="text-white">Home</Nav.Link>
            <Nav.Link href="/login" className="text-white">Login</Nav.Link>
            <Nav.Link href="/contact-interest" className="text-white">Cadastro</Nav.Link>
            <Nav.Link href="/dashboard" className="text-white">Dashboard</Nav.Link>
          </Nav>
        </Navbar.Collapse>
      </Container>
    </Navbar>
  );
}

export default NavbarHome;
